version: "3"
services:

  #MySQL Database for the application
  mysql_db:
    image: "mysql:8.0"
    container_name: mysql_db
    restart: always
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: theatre-management
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


  #Fron-end Angular Application
  frontend:
    build: ./front
    container_name: frontend
    ports:
      - 4200:80
    links:
      - backend

  #Back-end Spring Boot Application
  backend:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./spring-boot-server
    container_name: backend
    restart: always
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/theatre-management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
       - mysql_db
    links:
      - mysql_db
